# -*- coding: utf-8 -*-
"""MODIS Snow Cover Product Gap-filling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O10yhIeh3d3A2dYYzrRckzvZhFQ6bvN1
"""

!pip install xee
import ee
import geemap
import xee
import xarray as xr

ee.Authenticate()
ee.Initialize(
    project = 'ee-lavibas23',
    opt_url = 'https://earthengine-highvolume.googleapis.com'
)

!pip uninstall -y earthengine-api geemap
!pip install earthengine-api==0.1.398 geemap==0.32.0 xee

import ee
import geemap
import xarray as xr
import xee

ee.Authenticate()
ee.Initialize(
    project = 'ee-lavibas23',
    opt_url = 'https://earthengine-highvolume.googleapis.com'
)

# Define Langtang Basin approximate boundary (bounding box)
langtang = ee.Geometry.Rectangle([85.25, 28.05, 85.75, 28.40])

# Create a map
Map = geemap.Map(center=[28.2, 85.5], zoom=9)

# Add basin boundary
Map.addLayer(langtang, {'color': 'red'}, 'Langtang Basin')

Map

mod = (
    ee.ImageCollection("MODIS/061/MOD10A1")
    .filterDate('2020','2021')
    .select('NDSI_Snow_Cover')
)

mod

ds = xr.open_dataset(
    mod,
    engine = 'ee',
    crs = 'EPSG:4326',
    geometry = langtang,
    scale = 0.001
)

ds

ds.sel(time = ds.time.dt.month == 1).NDSI_Snow_Cover.plot(
    x = 'lon',
    y = 'lat',
    col = 'time',
    col_wrap = 7,
    robust = True
)

ds_rolling = ds.rolling(time = 10, center = True, min_periods = 1).median('time')

ds_fill = ds.fillna(ds_rolling)

ds_fill.sel(time = ds_rolling.time.dt.month == 1).NDSI_Snow_Cover.plot(
    x = 'lon',
    y = 'lat',
    col = 'time',
    col_wrap = 7,
    robust = True
)

!pip install netCDF4
import netCDF4

ds_fill.to_netcdf('snow_cover.nc')